In [1]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


np.ndarray는 array를 만드는 numpy 함수인가??

In [2]:
narray1 = np.ndarray([1,2,3])
narray1

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [3]:
narray2 = np.array([1,2,3])
narray2

array([1, 2, 3])

위 두 결과를 보면 뭔가 다른걸 알 수 있다. 

먼저, 첫번째 ndarray는 단순히 값을 입력하여 ndarray를 만드는 함수가 아닌, 데이터의 구조를 지정하여 데이터를 입력하는 함수이다.

아래 두번째 array는 실제 값을 입력하여 ndarray클래스를 만드는 함수임을 알 수 있다.

그러면, 도대체 왜 ndarray라는 피곤한 객체 타입(클래스)를 따로 만들어서 진입장벽과, 쓰기 귀찮음을 동시에 챙긴걸까?

그건 바로 아래에서 알 수 있다.

In [13]:
ndim1 = narray1.ndim
ndim2 = narray2.ndim
print(f"ndim1 : {ndim1}, ndim2 : {ndim2}")
# 차원 계단의 개수를 출력하는 함수임을 알 수 있다. 기왕 하는거 헷갈리지 않게 확실하게 해보자.
# 5단계짜리 ndarray를 만들어보자.
narray3 = np.ndarray([1,2,1,2,4])
print(f"narray3은 5단계 배열일까요? 네! narray3.ndim : {narray3.ndim}")
print(f"narray3.shape : {narray3.shape}, narray3.size : {narray3.size}, narray3.dtype : {narray3.dtype}")
print(narray3)

ndim1 : 3, ndim2 : 1
narray3은 5단계 배열일까요? 네! narray3.ndim : 5
narray3.shape : (1, 2, 1, 2, 4), narray3.size : 16, narray3.dtype : float64
[[[[[4.67296746e-307 1.69121096e-306 2.33646845e-307 1.11256817e-306]
    [1.06811422e-306 1.42417221e-306 1.11260619e-306 8.90094053e-307]]]


  [[[1.86919378e-306 1.06809792e-306 1.37962456e-306 1.69111861e-306]
    [1.78020169e-306 7.56605918e-307 5.33590898e-322 1.11253693e-308]]]]]


그런데, 아까 narray1.ndim을 직접 실험해보시면, narray1.ndim() 이런 식으로 쓰셨을 수도 있습니다. 하지만 이건 에러를 불러일으키는데요,

당연히 클래스의 함수(메소드)를 불러오는 거라 생각했는데 왜 에러가 날까요?

In [ ]:
# ndim, shape등등은 메소드가 아닌 클래스 변수이다.